[program:admin]
command=/usr/bin/yarn start -p 3002
directory=/app/admin
autostart=true
autorestart=true
stderr_logfile=/var/log/supervisor/admin.err.log
stdout_logfile=/var/log/supervisor/admin.out.log
environment=NODE_ENV="production",PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/app/admin/node_modules/.bin",NEXT_PUBLIC_REST_API_ENDPOINT="https://srcchi.top/backend",NEXT_PUBLIC_SHOP_URL="http://localhost:3000",APPLICATION_MODE="production",NEXT_PUBLIC_AUTH_TOKEN_KEY="AUTH_CRED",NEXT_PUBLIC_DEFAULT_LANGUAGE="en",NEXT_PUBLIC_ENABLE_MULTI_LANG="true",NEXT_PUBLIC_AVAILABLE_LANGUAGES="en,de,ar,fa",NEXT_PUBLIC_PUSHER_ENABLED="false",NEXT_PUBLIC_API_BROADCAST_DRIVER="log",NEXT_PUBLIC_PUSHER_APP_KEY="disabled",NEXT_PUBLIC_PUSHER_APP_CLUSTER="disabled",NEXT_PUBLIC_BROADCAST_AUTH_URL="disabled",NEXT_PUBLIC_PUSHER_DEV_MOOD="false"
user=root
stopasgroup=true
killasgroup=true
